import { useEffect, useState } from "react"
import Head from 'next/head'
import Nav from "@/components/Nav"
import {
  Container,
  UnselectableText,
  Icon,
} from '@/components/sharedstyles'

export default function Home() {
  const [isReady, setIsReady] = useState(false)

  useEffect(() => {
    setTimeout(() => {
      setIsReady(true)
    }, 1000);
  }, [])

  return (
    <Container>
      <Head>
        <title>SC V5 - SSR and CSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <h1>Both server-side rendering and client-side rendering with styled-components v5</h1>
      <h2>Server-Side Rendered</h2>
      <UnselectableText>
        This is supposed to be unselectable thanks to `user-select: none;`
      </UnselectableText>
      <p>
        <Icon />
      </p>
      <h2>Client-Side Rendered</h2>
      {isReady ? (
        <>
          <UnselectableText>
            This is supposed to be unselectable thanks to `user-select: none;`
          </UnselectableText>
          <p>
            <Icon />
          </p>
        </>
      ) : <p>loading...</p>}
    </Container>
  )
}
