import Head from 'next/head'
import Nav from "@/components/Nav"
import {
  Container,
  UnselectableText,
  Icon,
} from '@/components/sharedstyles'

export default function Ssr() {
  return (
    <Container>
      <Head>
        <title>SC V5 - SSR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <h1>Server-Side Rendering with styled-components v5</h1>
      <UnselectableText>
        This is supposed to be unselectable thanks to `user-select: none;`
      </UnselectableText>
      <p>
        <Icon />
      </p>
    </Container>
  )
}
